name: Run Schemathesis on Pull Requests
on: [pull_request]
jobs:

  api-tests:
    runs-on: ubuntu-20.04
    container: schemathesis/schemathesis:stable

    env:
      # A publicly available API schema location
      API_SCHEMA: '../../reference/subscribers.v3.yml'

    steps:
      
      # Runs positive Schemathesis tests with all checks enabled
      - env:
          X-AUTH-TOKEN: ${{ secrets.X_AUTH_TOKEN }}
        run: st run -H X-Auth-Token:"$X-Auth-Token" $API_SCHEMA --checks=all

      # comment to trigger test