name: Run Schemathesis on Pull Requests
on: [pull_request]
jobs:

  api-tests:
    runs-on: ubuntu-20.04
    container: schemathesis/schemathesis:stable

    env:
      # A publicly available API schema location      
      API_SCHEMA: 'https://raw.githubusercontent.com/bigcommerce/api-specs/github-action_schemathesis-test-01/reference/pages.v3.yml'
      X_AUTH: ${{ secrets.X_AUTH_TOKEN }}

    steps:
      
      # Runs positive Schemathesis tests with all checks enabled
      - run: st run -H "X-Auth-Token: $X_AUTH" --base-url https://api.bigcommerce.com $API_SCHEMA --checks=all

      # comment to trigger test